version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    env_file:
      - project-backend/.env
      - project-backend/config.env
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_ENV_ENDPOINT=http://backend:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
