---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: l00187746/backend:staging # backend image name
          imagePullPolicy: Always  # Ensures Kubernetes always pulls the latest image
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
      nodeSelector:
         nodegroup-role: worker-staging

---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: backend-staging
spec:
  selector:
    app: backend  # Match the labels of your backend pods
  ports:
    - protocol: TCP
      port: 5000  # Port exposed by the Service
      targetPort: 5000
      nodePort: 30003
  type: NodePort  # Internal service (not exposed externally)
