apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: prod
data:
  MONGO_ROOT_USER: "l00187746"
  MONGO_DB: "WednesdayAdventures"
  ADMIN_MAIL: "support@wednesdaysadventures.com"
  FRONTEND_URL: http://localhost:80"