apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: prod
data:
  MONGO_ROOT_USER: "l00187746"
  MONGO_DB: "WednesdayAdventures"
  ADMIN_MAIL: "support@wednesdaysadventures.com"
  FRONTEND_URL: k8s-default-frontend-9506ded24e-376539300.eu-west-1.elb.amazonaws.com"