---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: staging
data:
  MONGO_ROOT_USER: "l00187746"
  MONGO_DB: "WednesdayAdventures"
  ADMIN_MAIL: "support@wednesdaysadventures.com"
  PORT: "5000"