---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: prod
data:
  MONGO_ROOT_USER: "l00187746"
  MONGO_DB: "WednesdayAdventures"
  ADMIN_MAIL: "support@wednesdaysadventures.com"
  PORT: "5000"
  FRONTEND_URL: "http://k8s-prod-frontend-02d00d641e-1294408721.eu-west-1.elb.amazonaws.com"