---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: l00187746/frontend:latest  # frontend image
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_ENV_ENDPOINT
              value: "http://a595c6a27b9e64b8689b273f565d7b12-2128934366.eu-west-1.elb.amazonaws.com:5000"  # backend service name
      nodeSelector:
         nodegroup-role: worker-prod



---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # You can change this to 80 if you're not exposing it externally
  type: NodePort