---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: l00187746/wednesday-adventures-frontend  # frontend image
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_ENV_ENDPOINT
              value: "http://backend:5000"  # backend service name



---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # You can change this to 80 if you're not exposing it externally
  type: NodePort