apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: prod  # Replace with your namespace if needed
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;  # Redirect all routes to index.html
        }
