apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: prod
type: Opaque
data:
  MONGO_ROOT_PASSWORD: "V2VkbmVzZGF5QWR2ZW50dXJlczEyMw=="
  DATABASE: "bW9uZ29kYitzcnY6Ly9sMDAxODc3NDY6V2VkbmVzZGF5QWR2ZW50dXJlczEyM0BjbHVzdGVyMC5pZ3pzby5tb25nb2RiLm5ldC9XZWRuZXNkYXlBZHZlbnR1cmVzP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ=="
  JWT_SECRET: "b557e9a4ea66c3ed6ff03a19568b23f2be8bb18652da1e632403cd42c020c39eaa13727cddcaa80ba31cd17812635eb164f0e95886abad59e8be32bd1ec234b1"
   
  