name: Generate JSDoc

on:
  push:
    branches:
      - L00187746-Trivy-Sumathi

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Allow read access to repository contents
      actions: write  # Allow upload of artifacts and use of actions
      id-token: read  # Allow read access to identity token if needed
      artifacts: write  # Allow uploading artifacts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate JSDoc
        run: npx jsdoc -c jsdoc.json

      - name: Upload JSDoc as Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: jsdoc-artifact
          path: documentation/JSDoc
          retention-days: 10  # Store artifact for 7 days (adjust as needed)
