name: Generate JSDoc

on:
  push:
    branches:
      - L00187746-Trivy-Sumathi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate JSDoc
        run: npx jsdoc -c jsdoc.json

      - name: Upload JSDoc as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jsdoc-artifact
          path: documentation/JSDoc
          retention-days: 7  # Store artifact for 7 days (adjust as needed)
