name: Main_CI_Pipeline

on:
  push:
    branches:
      - main
      - develop
      - l00187927-WA-Jira18-CIPipeline
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Backend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest -f Dockerfile.backend .
      - name: Build Frontend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f Dockerfile.frontend .
      - name: Push Docker Images
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

  sbom_scan:
    runs-on: ubuntu-latest
    needs: build_docker_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/trivy
      - name: Generate SBOM Report
        run: trivy fs --format spdx-json -o sbom.json .
      - name: Upload SBOM Report
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom.json

  snyk_security_scan:
    runs-on: ubuntu-latest
    needs: build_docker_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Run Snyk Security Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --severity-threshold=high || echo "Snyk scan completed with issues"
      - name: Monitor vulnerabilities in Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --all-projects || echo "Snyk monitor completed with issues"

  owasp_zap_scan:
    runs-on: ubuntu-latest
    needs: snyk_security_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd project-backend && npm ci && npm start &
          cd ../frontend && npm ci && npm start &
      - name: Run ZAP Scan - Backend
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          cmd_options: '-T 120 -J zap_backend.json'
          fail_action: false
      - name: Run ZAP Scan - Frontend
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3001'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          cmd_options: '-T 120 -J zap_frontend.json'
          fail_action: false
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap_backend.json
            zap_frontend.json

  sonarcloud_analysis:
    runs-on: ubuntu-latest
    needs: build_docker_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Docker
        run: |
          sudo apt-get remove -y docker docker-engine docker.io containerd runc
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
      - name: Run SonarCloud Analysis
        run: |
          docker run --rm \
            -e SONAR_HOST_URL=https://sonarcloud.io \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -v $(pwd):/usr/src \
            sonarsource/sonar-scanner-cli:latest \
            -Dsonar.projectKey=SumathiD20_Wednesday_Adventures \
            -Dsonar.organization=sumathid20 \
            -Dsonar.sources=project-backend,frontend \
            -Dsonar.exclusions=**/node_modules/**,**/tests/** \
            -Dsonar.sourceEncoding=UTF-8

  generate_jsdoc:
    runs-on: ubuntu-latest
    needs: [build_docker_image, sonarcloud_analysis]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd project-backend && npm install
          cd ../frontend && npm install
      - name: Check if jsdoc.json exists
        run: |
          if [ ! -f "project-backend/jsdoc.json" ]; then
            echo "JSDoc config missing in project-backend"
            exit 1
          fi
          if [ ! -f "frontend/jsdoc.json" ]; then
            echo "JSDoc config missing in frontend"
            exit 1
          fi
      - name: Generate JSDoc
        run: |
          cd project-backend && npx jsdoc -c jsdoc.json --verbose
          cd ../frontend && npx jsdoc -c jsdoc.json --verbose
      - name: Upload JSDoc
        uses: actions/upload-artifact@v4
        with:
          name: jsdoc-documentation
          path: |
            project-backend/docs
            frontend/docs
