name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - l00187927-WA-Jira18-CIPipeline  # Trigger analysis on this branch
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (for Node.js projects)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          args: -Dsonar.branch.name=${{ github.ref }}
          projectBaseDir: .   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
