name: SonarCloud Analysis

on:
  push:
    branches:
      - l00187927-WA-Jira18-CIPipeline
  pull_request:
    branches:
      - l00187927-WA-Jira18-CIPipeline

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd project-backend
          npm ci

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          args: >
            -Dsonar.branch.name=${{ github.ref_name }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Quality Gate status to GitHub
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          args: "-Dsonar.login=${{ secrets.SONAR_TOKEN }}"
