name: SonarCloud Analysis with Docker

on:
  push:
    branches:
      - main
      - l00187927-WA-Jira18-CIPipeline   

  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan using Docker
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image with SonarCloud
      - name: Run SonarCloud Scan in Docker
        run: |
          docker run --rm \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -e SONAR_PROJECT_KEY=${{ github.repository }} \
            -v $GITHUB_WORKSPACE:/workspace \
            sonarsource/sonar-scanner-cli:latest \
            -Dsonar.projectKey=${{ github.repository }} \
            -Dsonar.sources=./src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
