name: OWASP ZAP Security Scan

on: [push, pull_request]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0  # Official ZAP action
      with:
        target: 'http://localhost:3000'  # Update to your application's URL
        cmd_options: '-a -J -r'  # Active scan with reports
        docker_image: 'ghcr.io/zaproxy/zaproxy:stable'  # Correct container registry
        
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: |
          zap-report.html
          zap-report.json
          zap-report.md
