name: OWASP Security Scan - Backend

on:
  push:
    branches:
      - main
      - develop
      - l00187927-WA-Jira18-CIPipeline
  pull_request:
    branches:
      - main
      - develop
      - l00187927-WA-Jira18-CIPipeline

jobs:
  owasp-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Move into the backend directory
    - name: Change to Backend Directory
      run: cd project-backend

    # Debug - Check if package.json exists in backend
    - name: Verify package.json exists
      run: |
        if [ ! -f project-backend/package.json ]; then
          echo "❌ package.json not found in project-backend!"
          exit 1
        fi
    # Debug - Show package.json dependencies
    - name: Show package.json Dependencies
      run: cat project-backend/package.json

    # Install Dependencies Properly
    - name: Install Dependencies
      run: |
        cd project-backend
        rm -rf node_modules package-lock.json  # Remove old dependencies
        npm install  # Fresh install
    # Debug - Check if node_modules and express exist
    - name: Verify Express Installation
      run: ls -R project-backend/node_modules || echo "❌ node_modules directory not found!"

    # Start Application Server in the Background
    - name: Start Application Server
      run: |
        cd project-backend
        nohup node index.js &  # Start the backend
        sleep 40  # Wait for the server to start
    # Verify Server is Running on Port 5000
    - name: Check if Server is Running
      run: |
        curl -I http://localhost:5000 || (echo "❌ Server did not start!" && exit 1)
    # Run OWASP Dependency-Check (SCA) for Backend
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "project-backend"
        path: "./project-backend"  # Run scan in backend directory
        format: "ALL"
        out: "./dependency-check-report"

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report   # Valid artifact name
        path: dependency-check-report

    # Run OWASP ZAP Full Scan on Backend (localhost:5000)
    - name: Run OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.11.0
      with:
        target: "http://localhost:5000"  # Ensure you're scanning the backend URL
        cmd_options: "-a"  # Add additional flags if necessary
        docker_name: ghcr.io/zaproxy/zaproxy:stable
        fail_action: false  # Set to false to avoid failing the action for scan findings
        allow_issue_writing: false  # Disable issue creation on GitHub

    - name: Upload OWASP ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report   # Valid artifact name
        path: zap.out

    # Fail Build on Critical/High Vulnerabilities
    - name: Fail Build on Critical/High Vulnerabilities
      run: |
        if [ ! -s dependency-check-report/dependency-check-report.json ]; then
          echo "⚠️ No dependency-check report found. Skipping failure check."
          exit 0
        fi
        # Count vulnerabilities by severity
        CRITICAL_COUNT=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity=="Critical")] | length' dependency-check-report/dependency-check-report.json)
        HIGH_COUNT=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity=="High")] | length' dependency-check-report/dependency-check-report.json)
        echo "🔍 Found vulnerabilities:"
        echo "   🔴 Critical: $CRITICAL_COUNT"
        echo "   🟠 High: $HIGH_COUNT"
        if [ "$CRITICAL_COUNT" -gt 0 ]; then
          echo "❌ Critical vulnerabilities found! Failing the build."
          exit 1
        fi
        if [ "$HIGH_COUNT" -gt 5 ]; then
          echo "❌ More than 5 High vulnerabilities found! Failing the build."
          exit 1
        fi
        echo "✅ No critical or excessive high vulnerabilities found. Proceeding..."
