name: ZAP Security Scan

on:
  push:
    branches:
      - l00187927-WA-Jira18-CIPipeline
      - main
      - develop

jobs:
  build-test-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install OWASP ZAP
      run: |
        sudo apt-get update
        sudo apt-get install zaproxy

    - name: Start ZAP in the background
      run: |
        nohup zaproxy -daemon -port 8080 &

    - name: Wait for ZAP to initialize
      run: |
        sleep 30

    - name: Run ZAP Security Scan
      run: |
        zap-cli quick-scan --start-url http://localhost:3000 || echo "ZAP scan completed with issues"

    - name: Stop ZAP
      run: |
        zap-cli shutdown || echo "Failed to stop ZAP"
