name: ZAP Security Scan

on:
  push:
    branches:
      - l00187927-WA-Jira18-CIPipeline
      - main
  pull_request:
    branches:
      - l00187927-WA-Jira18-CIPipeline
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Start Application (if needed)
        run: |
          docker-compose up -d  # Start services if using Docker
          sleep 10  # Wait for app to be ready
      
      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://localhost:3000'  # Change this to your app's URL
          api-key: ${{ secrets.ZAP_API_KEY }}
          fail-action: false  # Set to true if you want the job to fail on vulnerabilities

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP-Scan-Report
          path: report.html
