name: OWASP Security Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  owasp-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ------------------------------
    # OWASP Dependency-Check Scan
    # ------------------------------
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "Wednesday_Adventures"
        scan: "./"
        format: "ALL"  
        out: "./dependency-check-report"

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: dependency-check-report

    # ------------------------------
    # Run OWASP ZAP Baseline Scan
    # ------------------------------
    - name: Pull OWASP ZAP Docker Image
      run: docker pull owasp/zap2docker-stable

    - name: Run OWASP ZAP Baseline Scan
      run: |
        docker run --rm -v $(pwd):/zap/wrk:rw owasp/zap2docker-stable zap-baseline.py \
          -t "http://example.com" -r zap-report.html -a

    - name: Upload OWASP ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-security-report
        path: zap-report.html

    # ------------------------------
    # Fail Build on Critical Vulnerabilities
    # ------------------------------
    - name: Check for Critical Vulnerabilities
      run: |
        sudo apt-get install -y jq
        CRITICAL_COUNT=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity=="Critical")] | length' dependency-check-report/dependency-check-report.json)
        if [ "$CRITICAL_COUNT" -gt 0 ]; then
          echo "Critical vulnerabilities found! Failing the build."
          exit 1
        fi
