name: OWASP Security Scan

on:
  push:
    branches:
      - main
      - develop
      - l00187927-WA-Jira18-CIPipeline  
  pull_request:
    branches:
      - main
      - develop
      - l00187927-WA-Jira18-CIPipeline

jobs:
  owasp-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Start Application Server in the Background
    - name: Start Application Server
      run: |
        nohup npm start &  # Start the server in the background
        sleep 15  # Wait for the server to start

    # Verify Server is Running
    - name: Check if Server is Running
      run: curl -I http://localhost:3000 || (echo "Server did not start!" && exit 1)

    # Run OWASP Dependency-Check (SCA)
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "Wednesday_Adventures"
        path: "./"
        format: "ALL"
        out: "./dependency-check-report"

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: dependency-check-report

    # Run OWASP ZAP Full Scan
    - name: Run OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.11.0
      with:
        target: "http://localhost:3000"
        cmd_options: "-a"

    - name: Upload OWASP ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap.out

    # Fail Build on Critical/High Vulnerabilities
    - name: Fail Build on Critical/High Vulnerabilities
      run: |
        if [ ! -s dependency-check-report/dependency-check-report.json ]; then
          echo "⚠️ No dependency-check report found. Skipping failure check."
          exit 0
        fi
        # Count vulnerabilities by severity
        CRITICAL_COUNT=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity=="Critical")] | length' dependency-check-report/dependency-check-report.json)
        HIGH_COUNT=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity=="High")] | length' dependency-check-report/dependency-check-report.json)
        echo "🔍 Found vulnerabilities:"
        echo "   🔴 Critical: $CRITICAL_COUNT"
        echo "   🟠 High: $HIGH_COUNT"
        if [ "$CRITICAL_COUNT" -gt 0 ]; then
          echo "❌ Critical vulnerabilities found! Failing the build."
          exit 1
        fi
        if [ "$HIGH_COUNT" -gt 5 ]; then
          echo "❌ More than 5 High vulnerabilities found! Failing the build."
          exit 1
        fi
        echo "✅ No critical or excessive high vulnerabilities found. Proceeding..."
