name: ZAP Security Scan

on:
  push:
    branches:
      - l00187927-WA-Jira18-CIPipeline
      - main
      - develop

jobs:
  build-test-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install OWASP ZAP
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
        tar -xvzf ZAP_2.14.0_Linux.tar.gz
        sudo mv ZAP_2.14.0 /opt/zaproxy
        sudo ln -s /opt/zaproxy/zap.sh /usr/local/bin/zap

    - name: Start ZAP in the background
      run: |
        nohup zap -daemon -port 8080 &

    - name: Wait for ZAP to initialize
      run: |
        sleep 30

    - name: Run ZAP Security Scan
      run: |
        zap-cli quick-scan --start-url http://localhost:3000 || echo "ZAP scan completed with issues"

    - name: Stop ZAP
      run: |
  
