name: ZAP Security Scan

on:
  push:
    branches:
      - l00187927-WA-Jira18-CIPipeline
  pull_request:
    branches:
      - l00187927-WA-Jira18-CIPipeline

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://your-application-url.com'  # Replace with your application URL
          rules: 'rules.zap'  # Optional: Path to custom ZAP rules file
          format: 'html'  # Report format (html, json, etc.)
          output: 'zap-report.html'  # Output file name

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: zap-report
          path: zap-report.html
