name: OWASP Security Scan

on:
  push:
    branches:
      - main
      - develop
      - l00187927-WA-Jira18-CIPipeline  
  pull_request:
    branches:
      - main
      - develop
      - l00187927-WA-Jira18-CIPipeline

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # -----------------------------------------
    # OWASP Dependency-Check (Dependency Scanning)
    # -----------------------------------------
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "Wednesday_Adventures"
        path: "./"  # Scan the repository codebase
        format: "ALL"  # Generates JSON, XML, and HTML reports
        out: "./dependency-check-report"

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: dependency-check-report

    # -----------------------------------------
    # SonarQube Scan (Static Code Analysis)
    # -----------------------------------------
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: "https://sonarcloud.io"  

    # -----------------------------------------
    # Fail Build if Critical Vulnerabilities Found
    # -----------------------------------------
    - name: Fail Build on Critical Vulnerabilities
      run: |
        # Check if the JSON report exists and is not empty
        if [ ! -s dependency-check-report/dependency-check-report.json ]; then
          echo "⚠️ No dependency-check report found or it's empty. Skipping failure check."
          exit 0
        fi
        
        # Count critical vulnerabilities safely
        CRITICAL_COUNT=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity=="Critical")] | length' dependency-check-report/dependency-check-report.json)
        
        if [ "$CRITICAL_COUNT" -gt 0 ]; then
          echo "❌ Critical vulnerabilities found! Failing the build."
          exit 1
        else
          echo "✅ No critical vulnerabilities found. Proceeding..."
        fi
