name: ZAP Security Scan

on:
  push:
    branches:
      - l00187927-WA-Jira18-CIPipeline
  pull_request:
    branches:
      - l00187927-WA-Jira18-CIPipeline

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://your-application-url.com'  # Replace with your application URL
          rules_file_name: 'rules.zap'  # Optional: Path to custom ZAP rules file
          cmd_options: '-T 60'  # Optional: Additional ZAP command-line options
          issue_title: 'ZAP Security Scan Report'  # Optional: Title for GitHub issues
          fail_action: false  # Optional: Whether to fail the workflow if issues are found

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_json.json
            report_md.md
            report_html.html
