name: OWASP Security Scan

on:
  push:
    branches:
      - main
      - develop
      - l00187927-WA-Jira18-CIPipeline  # ✅ Ensure this branch is included
  pull_request:
    branches:
      - main
      - develop
      - l00187927-WA-Jira18-CIPipeline

jobs:
  owasp-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # ------------------------------
    # OWASP Dependency-Check Scan
    # ------------------------------
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "Wednesday_Adventures"
        path: "./"  # ✅ Scan the repository codebase
        format: "ALL"  # ✅ Generates JSON, XML, and HTML reports
        out: "./dependency-check-report"

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: dependency-check-report

    # ------------------------------
    # Fail Build on Critical Vulnerabilities
    # ------------------------------
    - name: Fail Build if Critical Vulnerabilities Found
      run: |
        CRITICAL_COUNT=$(jq '[.dependencies[].vulnerabilities[] | select(.severity=="Critical")] | length' dependency-check-report/dependency-check-report.json)
        if [ "$CRITICAL_COUNT" -gt 0 ]; then
          echo "❌ Critical vulnerabilities found! Failing the build."
          exit 1
        fi
      continue-on-error: false  # ✅ Ensures the pipeline fails on critical issues
