name: ZAP Security Scan

on:
  push:
    branches:
      - l00187927-WA-Jira18-CIPipeline
  pull_request:
    branches:
      - l00187927-WA-Jira18-CIPipeline

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   

      # Install dependencies for backend
      - name: Install backend dependencies
        run: |
          cd project-backend
          npm ci   

      # Install dependencies for frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci  

      # Start backend
      - name: Start the backend application
        run: |
          cd project-backend
          npm start &
        env:
          PORT: 3000  # Ensure the backend runs on port 3000

      # Start frontend
      - name: Start the frontend application
        run: |
          cd frontend
          npm start &
        env:
          PORT: 3001  # Ensure the frontend runs on port 3001

      # Wait for backend to start
      - name: Wait for backend to start
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Backend is up!"
              exit 0
            fi
            echo "Waiting for backend to start..."
            sleep 2
          done
          echo "Backend failed to start"
          exit 1

      # Wait for frontend to start
      - name: Wait for frontend to start
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3001 > /dev/null; then
              echo "Frontend is up!"
              exit 0
            fi
            echo "Waiting for frontend to start..."
            sleep 2
          done
          echo "Frontend failed to start"
          exit 1

      - name: Fix permissions
        run: sudo chmod -R 777 /home/runner/work/

      # Run ZAP scan for backend
      - name: Run ZAP Baseline Scan - Backend
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'  
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'  
          cmd_options: '-T 60 -J /home/runner/work/zap_backend.json'  
          fail_action: false  

      # Run ZAP scan for frontend
      - name: Run ZAP Baseline Scan - Frontend
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3001'  
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'  
          cmd_options: '-T 60 -J /home/runner/work/zap_frontend.json'  
          fail_action: false  

      # Upload Backend ZAP Report
      - name: Upload ZAP Report - Backend
        uses: actions/upload-artifact@v4
        with:
          name: zap-backend-report
          path: |
            /home/runner/work/**/zap_backend.json
            /home/runner/work/**/report_backend_json.json
            /home/runner/work/**/report_backend_md.md
            /home/runner/work/**/report_backend_html.html

      # Upload Frontend ZAP Report
      - name: Upload ZAP Report - Frontend
        uses: actions/upload-artifact@v4
        with:
          name: zap-frontend-report
          path: |
            /home/runner/work/**/zap_frontend.json
            /home/runner/work/**/report_frontend_json.json
            /home/runner/work/**/report_frontend_md.md
            /home/runner/work/**/report_frontend_html.html
