name: OWASP ZAP Security Scan

on: [push, pull_request]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    services:
      webapp:
        image: node:20
        ports:
          - 3000:3000
        working-directory: /app
        volumes:
          - ./:/app
        # Start your application here
        entrypoint: /bin/bash -c "npm install && npm start"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fix workspace permissions
      run: sudo chmod -R 777 $GITHUB_WORKSPACE

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://webapp:3000'  # Use service name instead of localhost
        cmd_options: '-a -J -r -j' 
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        fail_action: false

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: |
          report_html.html
          report_md.md
          report_json.json
