name: ZAP Security Scan

on:
  push:
    branches:
      - l00187927-WA-Jira18-CIPipeline
  pull_request:
    branches:
      - l00187927-WA-Jira18-CIPipeline

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Replace with your Node.js version

      - name: Install dependencies
        run: npm install  # Replace with your package manager and install command

      - name: Start the application
        run: npm start &  # Replace with your start command
        env:
          PORT: 3000  # Ensure the app runs on port 3000

      - name: Wait for the application to start
        run: sleep 10  # Wait for the app to start (adjust as needed)

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'  # Scan the locally running app
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable' 
          cmd_options: '-T 60' 
          fail_action: false  # Optional: Whether to fail the workflow if issues are found

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_json.json
            report_md.md
            report_html.html
